[package]
name = "praytimes-cli"
version = "0.1.0"
edition = "2021"
authors = ["Max Bas MaxBaseCode@Gmail.Com","Ehsan ehsan2003.2003.382@gmail.com"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.26"
clap = { version = "4.3.22", features = ["derive","color"] }
praytimes = { path = "../../lib/praytimes",features =["serde"]}
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.105"
